# Catalog of frequently used repositories for repo_fuse
# Each [[repo]] block describes one project. Adjust entries to suit your workflow.

[[repo]]
name = "sample-service"
description = "Node service template"
url = "git@github.com:your-github-username/sample-service.git"
branch = "main"
# Optional setup commands run after cloning (executed inside the repo directory)
setup = [
  "npm install",
  "npm run build"
]

[[repo]]
name = "sample-ui"
description = "React UI starter"
url = "git@github.com:your-github-username/sample-ui.git"
setup = [
  "pnpm install",
  "pnpm run dev"
]

# You can add more fields per repo if needed (e.g., target_subdir, editor). The
# helper treats unknown keys as metadata and exposed via --info.
